.\" Man page written by Emanuele Petriglia for xfce4-panel-profiles.
.TH XFCE4-PANEL-PROFILES "1" "September 2020" "xfce4-panel-profiles 1.0.10" "User Commands"
.
.SH Name
xfce4-panel-profiles \- A simple application to manage Xfce panel layouts
.
.SH SYNOPSIS
\fBxfce4-panel-profiles\fR [load|save \fIPATH\fR]
.
.SH DESCRIPTION
\fBxfce4-panel-profiles\fP is a simple application to manage Xfce panel layouts.
It allows you to \fIapply\fP, \fIsave\fP, \fIremove\fP, \fIexport\fP,
\fIimport\fP a panel layout as a profile. You can, as example, backup the
current panel layout, or import a previously exported panel profile.

\fBxfce4-panel-profiles\fP is a \fIGUI application\fP, but it can be also used
via command line with limited features.
.
.SH COMMANDS
.TP
\fBload\fP \fIPATH\fP
Load and apply a previously exported \fIPATH\fP panel profile.
.TP
\fBsave\fP \fIPATH\fP
Save the current panel layout as \fIPATH\fP. The profile's name should end
with \fItar.bz2\fP for clarity.
.
.SH FILES
.TP
.I ~/.local/share/xfce4-panel-profiles
User's custom panel profiles storage directory.
.TP
.I /usr/share/xfce4-panel-profiles/layouts
System provided panel profiles storage directory.
.
.SH EXAMPLES
.TP
.B xfce4-panel-profiles save backup.tar.bz2
Make a backup of current panel layout.
.
.TP
.B xfce4-panel-profiles load backup.tar.bz2
Load and apply the previously exported panel layout.
.
.SH SEE ALSO
.BR xfce-panel (1)
.
.SH AUTHORS
.TP
2015-2020
.MT bluesabre@xfce.org
Sean Davis
.ME
.
.TP
2013
.MT a.j.buxton@gmail.com
Alistair Buxton
.ME
.
.SH REPORTING BUGS
Visit the
.UR https://docs.xfce.org/apps/xfce4-panel-profiles/bugs
reporting bus
.UE
page to view currently open bug reports and instructions on reporting new bugs
or submitting bugfixes.
